// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm2Zzzq-IFgBlHATrW6Ny9onSKNdQ-wzk',
    appId: '1:25434518470:web:f8456ae50d4546fc3c38c7',
    messagingSenderId: '25434518470',
    projectId: 'note-app-b8d9e',
    authDomain: 'note-app-b8d9e.firebaseapp.com',
    storageBucket: 'note-app-b8d9e.appspot.com',
    measurementId: 'G-DTZQFK10P6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTHUKr8yp4iUI9tp8I9gbR-ZHelZAuFZE',
    appId: '1:25434518470:android:a68808b725d53f8c3c38c7',
    messagingSenderId: '25434518470',
    projectId: 'note-app-b8d9e',
    storageBucket: 'note-app-b8d9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-sGF9BDk-o-i1WgZ1qinoMB8e2crC1Yg',
    appId: '1:25434518470:ios:77d57f96a46cbe743c38c7',
    messagingSenderId: '25434518470',
    projectId: 'note-app-b8d9e',
    storageBucket: 'note-app-b8d9e.appspot.com',
    androidClientId: '25434518470-cci0s5vlvq61ualp6q5i70v88c07pqnp.apps.googleusercontent.com',
    iosClientId: '25434518470-akkqm79ikjkjahcfdrcbf8mp0jdpbpsm.apps.googleusercontent.com',
    iosBundleId: 'com.segs.noteapp.dddtodoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-sGF9BDk-o-i1WgZ1qinoMB8e2crC1Yg',
    appId: '1:25434518470:ios:77d57f96a46cbe743c38c7',
    messagingSenderId: '25434518470',
    projectId: 'note-app-b8d9e',
    storageBucket: 'note-app-b8d9e.appspot.com',
    androidClientId: '25434518470-cci0s5vlvq61ualp6q5i70v88c07pqnp.apps.googleusercontent.com',
    iosClientId: '25434518470-akkqm79ikjkjahcfdrcbf8mp0jdpbpsm.apps.googleusercontent.com',
    iosBundleId: 'com.segs.noteapp.dddtodoapp',
  );
}
